{{ if .Values.cronJob.enabled }}
{{- range $name, $job := .Values.cronJob.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.name" $ }}-{{$name}}
  namespace: {{ include "app.namespace" $ }}
  labels:
    {{- include "chart.commonLabels" (merge (deepCopy $) (dict "suffixName" $name)) | indent 4 }}
    {{- if $.Values.cronJob.labels }}
    {{- range $key, $value := $.Values.cronJob.labels }}
    {{$key}}: {{$value | quote}}
    {{- end }}
    {{- end }}
    {{- if $job.labels }}
    {{- include "chart.renderLabels" $job.labels | indent 4 }}
    {{- end }}
  annotations:
    {{- include "chart.commonAnnotations" $ | indent 4 }}
    {{- if $.Values.cronJob.annotations }}
    {{- range $key, $value := $.Values.cronJob.annotations }}
    {{$key}}: {{$value | quote}}
    {{- end }}
    {{- end }}
    {{- if $job.annotations }}
    {{- include "chart.renderLabels" $job.annotations | indent 4 }}
    {{- end }}
spec:
  suspend: {{ $job.suspend | default false }}
  schedule: {{ $job.schedule | quote }}
  concurrencyPolicy: {{ $job.concurrencyPolicy | default "Replace" }}
  {{- if hasKey $job "startingDeadlineSeconds" }}
  startingDeadlineSeconds: {{ int $job.startingDeadlineSeconds }}
  {{- else }}
  startingDeadlineSeconds: 30
  {{- end }}
  {{- if hasKey $job "timeZone" }}
  timeZone: {{ $job.timeZone | quote }}
  {{- end }}
  {{- if hasKey $job "successfulJobsHistoryLimit" }}
  successfulJobsHistoryLimit: {{ int $job.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if hasKey $job "failedJobsHistoryLimit" }}
  failedJobsHistoryLimit: {{ int $job.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      {{- include "chart.jobSpec" (dict "global" $.Values.cronJob "job" $job) | indent 6 }}
      {{- $context :=  merge (dict "resourceType" "cronJob" "name" $name "Chart" $.Chart "Root" $) $job }}
      template:
      {{- include "chart.podTemplate" $context | nindent 8 }}
{{- end }}
{{- end }}
