{{ if .Values.job.enabled }}
{{- range $name, $job := .Values.job.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.name" $ }}-{{$name}}
  namespace: {{ include "app.namespace" $ }}
  labels:
    {{- $newContext := merge (deepCopy $) (dict "suffixName" $name) -}}
    {{- include "chart.commonLabels" $newContext | indent 4 }}
    {{- if $.Values.job.labels }}
    {{- range $key, $value := $.Values.job.labels }}
    {{$key}}: {{$value | quote}}
    {{- end }}
    {{- end }}
    {{- if $job.labels }}
    {{- include "chart.renderLabels" $job.labels | indent 4 }}
    {{- end }}
  annotations:
    {{- include "chart.commonAnnotations" $ | indent 4 }}
    {{- if $.Values.job.annotations }}
    {{- range $key, $value := $.Values.job.annotations }}
    {{$key}}: {{$value | quote}}
    {{- end }}
    {{- end }}
    {{- if $job.annotations }}
    {{- include "chart.renderLabels" $job.annotations | indent 4 }}
    {{- end }}
spec:
  suspend: {{ $job.suspend | default false }}
  {{- include "chart.jobSpec" (dict "global" $.Values.job "job" $job) | indent 2 }}
  {{- $context :=  merge (dict "resourceType" "job" "name" $name "Chart" $.Chart "Root" $newContext) $job }}
  template:
  {{- include "chart.podTemplate" $context | nindent 4 }}

{{- end }}
{{- end }}
