{{ if .Values.job.enabled }}
{{- range $name, $job := .Values.job.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.name" $ }}-{{$name}}
  namespace: {{ include "app.namespace" $ }}
  labels:
    {{- $newContext := set $ "suffixName" $name }}
    {{- include "chart.commonLabels" $newContext | indent 4 }}
    {{- if $.Values.job.labels }}
    {{- range $key, $value := $.Values.job.labels }}
    {{$key}}: {{$value | quote}}
    {{- end }}
    {{- end }}
    {{- range $job.labels }}
    {{ .key }}: {{ .value | quote }}
    {{- end }}
  annotations:
    {{- include "chart.commonAnnotations" $ | indent 4 }}
    {{- if $.Values.job.annotations }}
    {{- range $key, $value := $.Values.job.annotations }}
    {{$key}}: {{$value | quote}}
    {{- end }}
    {{- end }}
    {{- range $job.annotations }}
    {{.key}}: {{.value | quote}}
    {{- end }}
spec:
  {{- $specContext := dict "job" $job "globalSpec" $.Values.job "resourceType" "job" "name" $name "Chart" $.Chart "Root" $ }}
  {{- include "chart.jobSpec" $specContext | trim | nindent 2 }}

{{- end }}
{{- end }}
