{{- if .Values.waf.enabled -}}
{{- range .Values.waf.entries }}
---
apiVersion: metacontroller.glueops.dev/v1alpha1
kind: WebApplicationFirewall
metadata:
  name: {{ include "app.name" $ }}-{{ .name }}
  namespace: {{ include "app.namespace" $ }}
spec:
  domains:
  {{- range .hosts }}
    - {{ .hostname | quote }}
  {{- end }}
  {{- if .webAclName }}
  web_acl_name: {{ .webAclName | quote }}
  {{- end }}
  {{- if .customCertificateSecretStorePath }}
  custom_certificate_secret_store_path: {{ .customCertificateSecretStorePath | quote }}
  {{- end }}
{{- end }}
{{- end }}
